// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTLnu3phKg74w1Os5cBLbxaDtIxqrr1U',
    appId: '1:1096286447873:web:a1216ef518f92af761d300',
    messagingSenderId: '1096286447873',
    projectId: 'prjskb-37490',
    authDomain: 'prjskb-37490.firebaseapp.com',
    storageBucket: 'prjskb-37490.appspot.com',
    measurementId: 'G-1Q3JZ32WKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4F3eCnfiJ_5ruKpYNQ3OBlAtLLEIHvWM',
    appId: '1:1096286447873:android:81e681f5156ca90061d300',
    messagingSenderId: '1096286447873',
    projectId: 'prjskb-37490',
    storageBucket: 'prjskb-37490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl3GdVWWieeE_BczBxCRqQ6tVl4lJ_-rk',
    appId: '1:1096286447873:ios:5d005d82ab16513f61d300',
    messagingSenderId: '1096286447873',
    projectId: 'prjskb-37490',
    storageBucket: 'prjskb-37490.appspot.com',
    iosBundleId: 'com.example.sbkprj',
  );
}
